### ISSUE TITLE
Requires lodash, which isn't in package.json dependencies

### ISSUE THREAD

**Issue by mildmojo** [CraigglesO/torrent-parser#2]
This module requires `lodash`, but it's not specified as a dependency in `package.json`, so it's not included at install time. Requiring the module immediately bombs out.

```
$ npm install torrent-parser
fix-torrent-filenames@1.0.0 /home/mildmojo/code/fix-torrent-filenames
└── torrent-parser@1.1.0 
$ node -e "require('torrent-parser')"
module.js:457
    throw err;
    ^

Error: Cannot find module 'lodash'
    at Function.Module._resolveFilename (module.js:455:15)
    at Function.Module._load (module.js:403:25)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/mildmojo/code/fix-torrent-filenames/node_modules/torrent-parser/out/torrent-parser.js:6:11)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
```

**Comment by CraigglesO** [comment]
Thanks for bringing this to my attention. of course you can just install manually for now:
`npm install --save lodash`

**Comment by CraigglesO** [comment]
FIXED.

Again, thanks.

**Comment by mildmojo** [comment]
Thank you! :+1:
